#!/bin/bash

B=`tput bold`    #BOLD
D=`tput dim`     #DIM
U=`tput sgr 0 1` #UNDERLINE
U2=`tput smul`   #UNDERLINE2
NOU=`tput rmul`  #NO UNDERLINE
H=`tput smso`    #HIGHLIGHT
X=`tput sgr0`    #RESET
C='tput setaf '  #COLOR

function msghelp(){
        echo "Valid options:"
        echo "(w)warning,(g)greet,(e)bad|negative|error,(g|o)good|okay,(b)bold,(u)underline,(l)underline+bold,(n)normal";
        exit;
}

if [ -t 0 ]; then
        if   [ $# -lt 1 ]; then
                msghelp;
        fi
else
        if [[ -z "$2" ]]  ; then
                if test -t 0; then PIPE=0; echo ""; else PIPE=1 MSG="$(cat -)"; fi
                set -- $1 $MSG
        fi
fi

while getopts ':w:g:e:o:g:b:u:l:n' FLAG ; do
shift
case "$FLAG" in
        w|warning       ) i=3; c=`$C$i` && echo $c$H$@$X ;;
        g|greet         ) i=6; c=`$C$i` && echo $c${B}$@$X;;
        e|bad|negative  ) i=1; c=`$C$i` && echo $c${H}$@$X;;
        g|good|okay     ) i=2; c=`$C$i` && echo $c${B}$@$X;;
        b|bold          )       c=`$C`  && echo ${B}$@$X;;
        u|ul            )       c=`$C`  && echo ${U}$@$X;;
        l|ulbold        ) i=2; c=`$C$i` && echo $c${U2}$@$X;;
        n|normal        ) i=2; c=`$C$i` && echo $c$@$X;;
        \?              ) msghelp ;;
esac
done

#scenario 1  - echo abcd | msg2 -g
#scenario 1b - printf xyz| msg2 -l
#scenario 2  - cat  x.sh | msg2 -w
#scenario 3  - msg2 -b wow

