[General]
hotkey=Ctrl+Space
showTray=true
telemetry=true
terminal=Mate-Terminal

[applications_xdg]
enabled=true

[calculator_qalculate]
enabled=true

[datetime]
enabled=true

[system]
enabled=true

[terminal]
enabled=true

[widgetsboxmodel]
alwaysOnTop=true
clearOnHide=false
clientShadow=true
displayScrollbar=false
followCursor=true
hideOnFocusLoss=true
historySearch=true
itemCount=5
quitOnClose=false
showCentered=true
systemShadow=true
